name: Dev deployment
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  run-deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "dev"
      runner: "dev"
      env_file: "dev.env"
      port: "${{vars.PORT}}"
    secrets: inherit