name: Production deployment
on:
  workflow_dispatch:
jobs:
  run-deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "production"
      runner: "prod"
      env_file: "production.env"
    secrets: inherit