name: Run tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies  
        run: npm ci
  test: 
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Run tests
        run: npm run test